### ISSUE TITLE
Feature request: fetch guests (i.e. attendees)

### ISSUE THREAD

**Issue by benjaminvdb** [allenporter/gcal_sync#46]
It would be great if we can fetch the guests (i.e. attendees) of an event, perhaps in the form of:

```json
[
    {
        "name": "John Doe",
        "email": "john.doe@biz.com"
    },
    {
        "name": "Jane Doe",
        "email": "jane.doe@biz.com"
    }
]
```

Context: this library is being used in the [Home Assistant Google Calendar integration](https://github.com/home-assistant/core/tree/dev/homeassistant/components/google). If I know I'm in my kitchen (using presence detection) and I have a meeting, I'd like Google Assistant to notify me about this. I tend to create events for myself without guests (e.g. focus time) and I don't need to trigger automations on those.

**Comment by allenporter** [comment]
Really cool suggestion.

I feel like the example you gave was very compelling.  I think of two possible ways to consider this.

- Dump the data from the calendar API into the home assistant data (entity or calendar event in the trigger). It might not be standard across other calendars so we'd have to work through a generic way to add this to the data model

- Actually associating the guests with People in home assistant which might be more powerful and potentially useful by other integrations. This might get more interest from the dev community about other things we can connect and power.

Going to keep thinking about this...

**Comment by allenporter** [comment]
My other thought is that location may also be an interesting similarly shaped attribute.

(kow who is invited and where they should be)

**Comment by allenporter** [comment]
My other thought is that location may also be an interesting similarly shaped attribute.

(know who is invited and where they should be)

**Comment by benjaminvdb** [comment]
Thanks for giving this some thought! Are you also the maintainer for the HA integration?

> Dump the data from the calendar API into the home assistant data (entity or calendar event in the trigger). It might not be standard across other calendars so we'd have to work through a generic way to add this to the data model

Yes, I was thinking about something like this. I'm not too familiar with how HA works, but I was assuming I could attach something like a `data` dictionary to the trigger events that I can then handle in HA. I was about to write this myself, but noticed guests aren't exposed from this library, which brought me to this feature request.

> Actually associating the guests with People in home assistant which might be more powerful and potentially useful by other integrations. This might get more interest from the dev community about other things we can connect and power.

This sounds very cool. Most of the people I meet with aren't a `Person` entity in my HA instance, though I can see its use. I think the `gcal-sync` library still would need to be extended to include guests in its data model though, am I right?
