### ISSUE TITLE
coroutine '_ScriptRun.async_run' was never awaited

### ISSUE THREAD

**Issue by luca-angemi** [allenporter/gcal_sync#482]
Since HA 2024.5.0b0 I've this kind of messages in the log

```
2024-04-25 17:46:30.685 WARNING (MainThread) [py.warnings] /usr/local/lib/python3.12/site-packages/gcal_sync/model.py:100: RuntimeWarning: coroutine '_ScriptRun.async_run' was never awaited
for k, v in values.items():
```

**Comment by allenporter** [comment]
Appreciate the report. I'm a little confused about the error message here given `_ScriptRun` isn't running in gcal code

**Comment by allenporter** [comment]
OK, i would prefer if the issue were filed in the home assistant repo and the entire bug report template filled out (includes additional requests for details that could help with diagnosis including the diagnostics output). Shall we move this conversation to a new issue report in the core repo?

**Comment by luca-angemi** [comment]
Re diagnostic output i don't have anything at the moment. You want me to open the issue with the same info as here?

**Comment by allenporter** [comment]
Diagnostics is a specific thing in the UI https://www.home-assistant.io/docs/configuration/troubleshooting/#download-diagnostics that downloads a json file.

If you still see the log output then yeah could be useful to open an issue in core
