### ISSUE TITLE
Issues with narrow dependency ranges

### ISSUE THREAD

**Issue by cdce8p** [allenporter/gcal_sync#58]
The library pins specific versions of `aiohttp` and `pydantic`. Even if those are the most recent versions and always updated, these can easily cause dependency conflicts. For example, just a few hours ago pydantic `1.9.1` was released which now causes this error for Home Assistant.
```
gcal-sync 0.8.0 has requirement pydantic==1.9.0, but you have pydantic 1.9.1.
```

For (python) libraries, it's usually better to specific just a min supported version. That would allow for better compatibility with applications which depend on it. Only apps themselves should pin specific versions.

https://github.com/allenporter/gcal_sync/blob/9545ed239c2e1fa507998f4d730411c48e06ad46/setup.cfg#L18-L20

/CC: @allenporter

**Comment by allenporter** [comment]
Thanks, sorry about that, I'll send a fix and pr bump.

**Comment by allenporter** [comment]
Releasing 0.8.1 w/ the fix
